hmrc/amls-estate-agency-business-frontend

app/pages/EabServicesProvidedPage.scala, app/views/CheckYourAnswersView.scala.html, app/views/EabServicesProvidedView.scala.html, app/views/IndexView.scala.html, app/views/PenalisedEstateAgentsActDetailView.scala.html, app/views/PenalisedEstateAgentsActView.scala.html, app/views/PenalisedProfessionalBodyDetailView.scala.html, app/views/PenalisedProfessionalBodyView.scala.html, app/views/RedressSchemeDetailView.scala.html, app/views/RedressSchemeView.scala.html, app/views/SessionExpiredView.scala.html, app/views/UnauthorisedView.scala.html, app/views/WhatYouNeedView.scala.html, app/views/components/input_checkboxes.scala.html, app/views/components/input_date.scala.html, app/views/components/input_radio.scala.html, app/views/components/input_text.scala.html, app/views/components/input_yes_no.scala.html, app/views/components/submit_button.scala.html, conf/app.routes, conf/messages.en, test/views/PenalisedEstateAgentsActViewSpec.scala, test/views/PenalisedProfessionalBodyViewSpec.scala, test/views/RedressSchemeViewSpec.scala, test/views/ViewSpecBase.scala, test/views/behaviours/IntViewBehaviours.scala, test/views/behaviours/StringViewBehaviours.scala, test/views/behaviours/ViewBehaviours.scala, test/views/behaviours/YesNoViewBehaviours.scala
This ticket was to make sure the content we currently have in amls-frontend matches the content displayed on the new EAB microservice
Unit and manually tested
=> Amls 5543 - Copying existing content over from amls-frontend

app/views/WhatYouNeedView.scala.html, conf/messages.en, test/views/WhatYouNeedViewSpec.scala
What you need content changes
Manual and unit tests done.
=> AMLS-4970 | What you need content changes

app/config/FrontendAppConfig.scala, conf/application.conf, conf/prod.routes, release_notes/AMLS-5537.txt
As above.
https://github.com/hmrc/mdtp-frontend-routes/pull/1317
https://github.com/hmrc/mdtp-frontend-routes/pull/1318
https://github.com/hmrc/app-config-base/pull/2960
- manually
- unit tests
=> AMLS-5537 | Updated configuration

app/config/FrontendAppConfig.scala, app/views/GovukWrapper.scala.html, conf/application.conf, release_notes/AMLS-5536.txt
=> Amls 5536 - Added GTM to service

project/AppDependencies.scala, project/plugins.sbt, release_notes/AMLS-5705.txt
As above.
- none 
- regression, unit tests
=> Amls 5705 | Libraries upgrade

README.md, app/controllers/actions/IdentifierAction.scala
=> Add readme file

app/assets/javascripts/amlsestateagencybusinessfrontend.js, app/views/components/button_link_with_id.scala.html, release_notes/AMLS-5835.txt
=> AMLS-5835 | Updated links that look like buttons to properly mimic the behaviour of a button element

app/views/components/input_date.scala.html, release_notes/AMLS-5722.txt
This is a rebased version of AMLS-5722 for commit signing. The ticket has been tested and reviewed already but could use a quick once over on GitHub to check it looks the same.
Fully
=> AMLS-5722 | Changed date input and added release notes

app/assets/javascripts/characterCount.js, app/assets/stylesheets/partials/_amls.scss, app/assets/stylesheets/partials/_forms.scss, app/views/GovukWrapper.scala.html, app/views/PenalisedEstateAgentsActDetailView.scala.html, app/views/PenalisedProfessionalBodyDetailView.scala.html, app/views/components/input_textarea.scala.html, release_notes/AMLS-5831.txt
This is a rebase of AMLS-5831 for commit signing to be approved. This has been fully tested and review but could use a once over to make sure there is no difference between this and the original branch.
https://github.com/hmrc/amls-estate-agency-business-frontend/pull/26
Fully
=> Amls 5831 rebase

app/views/components/input_date.scala.html, release_notes/AMLS-5913.txt, test/views/components/inputDateSpec.scala
Fix aria-describedby where there is an error and hint text
N/A
Local + Unit
=>  AMLS-5913 | Fix aria-describedby where there is an error and hint text

app/models/UserAnswers.scala, app/models/package.scala, release_notes/AMLS-5848.txt, test/models/RichJsValueSpec.scala
Fix such that empty (null) records are not written to mongo where questions are not asked no answered. 
N/A
Unit + Local
=> Amls 5848 rebase

app/views/CheckYourAnswersView.scala.html, app/views/components/answer_row.scala.html
Add ID to CYA change link
N/A
Local + Unit
=> Add ID to CYA change link

app/assets/stylesheets/partials/_forms.scss, app/navigation/Navigator.scala, app/utils/CheckYourAnswersHelper.scala, app/views/CheckYourAnswersView.scala.html, app/views/ClientMoneyProtectionSchemeView.scala.html, app/views/EabServicesProvidedView.scala.html, app/views/GovukWrapper.scala.html, app/views/MainTemplate.scala.html, app/views/PenalisedEstateAgentsActView.scala.html, app/views/PenalisedProfessionalBodyView.scala.html, app/views/RedressSchemeView.scala.html, app/views/ViewUtils.scala, app/views/components/answer_row.scala.html, app/views/components/answer_section.scala.html, app/views/components/error_summary_with_id.scala.html, app/views/components/input_checkboxes.scala.html, conf/messages.en, release_notes/AMLS-5905.txt, test/navigation/NavigatorSpec.scala, test/utils/CheckYourAnswersHelperSpec.scala, test/views/components/inputCheckboxesSpec.scala
As above. There are also some slight changes to routing from/to CYA page. While testing noticed that gtm script is not within header content, so corrected it.
- none
- manually
- unit tests
=> Amls 5905 | EAB microservice accessibility fixes

project/AppDependencies.scala, project/build.properties, project/plugins.sbt, release_notes/AMLS-5751.txt
=> Amls 5751 | Updated app dependencies

build.sbt, project/plugins.sbt
Fix broken build in line with BDOG-612
N/A
Local
=> Fix broken build in line with BDOG-612

build.sbt
=> Bump major version

app/views/components/input_checkboxes.scala.html, release_notes/AMLS-5938.txt
As above.
- none
- manually
- wave
=> Amls 5938 | Linked aria described by to hint for checkboxes

app/assets/javascripts/characterCount.js, release_notes/AMLS-5917.txt
=> Amls 5917 | Remove TODO from code

app/config/FrontendAppConfig.scala, app/views/GovukWrapper.scala.html, conf/application.conf, conf/messages.en, release_notes/AMLS-5842.txt, release_notes/AMLS-5924.txt
This is linked to the frontend repo - https://github.com/hmrc/amls-frontend/pull/1477
Manually
=> Amls 5842 - Accessibility statement + footer link + toggle

app/assets/stylesheets/partials/_amls.scss, app/assets/stylesheets/partials/_forms.scss, release_notes/AMLS-5935.txt
=> Amls 5935 | Added styling for character counter error message

app/views/GovukWrapper.scala.html
=> AMLS-BetaHeaderRemoval | Beta banner removal

app/filters/AllowListFilter.scala, test/filters/AllowListFilterSpec.scala
replacing usages of whitelist/ blacklist with allowList/ denyList
sbt clean compile test
=> DLS-3126 updated language

app/config/FrontendAppConfig.scala, app/views/GovukWrapper.scala.html, conf/application.conf, project/AppDependencies.scala, test/controllers/CheckYourAnswersControllerSpec.scala, test/controllers/ClientMoneyProtectionSchemeControllerSpec.scala, test/controllers/DateOfChangeControllerSpec.scala, test/controllers/EabServicesProvidedControllerSpec.scala, test/controllers/PenalisedEstateAgentsActControllerSpec.scala, test/controllers/PenalisedEstateAgentsActDetailControllerSpec.scala, test/controllers/PenalisedProfessionalBodyControllerSpec.scala, test/controllers/PenalisedProfessionalBodyDetailControllerSpec.scala, test/controllers/RedressSchemeControllerSpec.scala, test/controllers/UnauthorisedControllerSpec.scala
=> Dls 3204 Accessibility Statements

conf/application.conf, conf/logback.xml, project/AppDependencies.scala
Signed-off-by: Sean Murray <sean.murray@digital.hmrc.gov.uk>
=> [SM][DLS-6580] replaced simplereactive-mongo with hmrc-mongo

app/views/template/Layout.scala.html, conf/application.conf, test/resources/test.application.conf
=> CSP config updates

app/config/FrontendAppConfig.scala, conf/application.conf
=> exit survey update

app/filters/SessionIdFilter.scala, build.sbt, project/AppDependencies.scala, project/plugins.sbt, test/connectors/AMLSBackEndConnectorSpec.scala, test/connectors/AMLSConnectorSpec.scala, test/controllers/ClientMoneyProtectionSchemeControllerSpec.scala, test/controllers/DateOfChangeControllerSpec.scala, test/controllers/EabServicesProvidedControllerSpec.scala, test/controllers/PenalisedEstateAgentsActControllerSpec.scala, test/controllers/PenalisedEstateAgentsActDetailControllerSpec.scala, test/controllers/PenalisedProfessionalBodyControllerSpec.scala, test/controllers/PenalisedProfessionalBodyDetailControllerSpec.scala, test/controllers/RedressSchemeControllerSpec.scala, test/controllers/actions/DataRetrievalActionSpec.scala, test/resources/test.application.conf, test/utils/ControllerHelperSpec.scala
=> Play 3.0 dependency upgrade

app/views/template/Layout.scala.html
=> DDCYLS-4101 Adding margin/padding to Layout

app/views/PenalisedProfessionalBodyView.scala.html
=> Reverting margin size back for consistency

app/forms/DateOfChangeFormProvider.scala, app/forms/mappings/LocalDateFormatter.scala, app/forms/mappings/Mappings.scala, app/views/DateOfChangeView.scala.html, app/views/components/DateErrorSummary.scala.html, conf/app.routes, conf/messages.en, test/forms/DateOfChangeFormProviderSpec.scala, test/forms/mappings/DateMappingsSpec.scala, test/forms/mappings/LocalDateFormatterSpec.scala
=> Ddcyls 5548 - Date errors do not target single fields EAB [UCD req'd]

README.md
=> DDCYLS-6374 - ReadMe update 

precheck.sh
=> DDCYLS-6655 - Adding precheck sh file

build.sbt, project/AppDependencies.scala, project/plugins.sbt
=> DDCYLS-6912 - dependency upgrade
